# Generated by Django 5.1.4 on 2025-01-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchlist',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='episodes',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userwatchlist',
            name='score',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
